// PRODUCT_FAMILY axis: 21 real tags + OTHER residual. Source: ontology_registry_candidate_v1.json,
// validated in CUSTOMER-INTELLIGENCE-R2-A00.1C-ontology-review-closure.md Section 8 (full 2011-product
// catalog check â€” every family confirmed KEEP, no SPLIT/MERGE/RENAME/DROP needed).

import type { CommercialProductOntologyTag } from './contracts.js';

export const productFamilyTags: readonly CommercialProductOntologyTag[] = [
  {
    axis: 'PRODUCT_FAMILY',
    code: 'BARBELL',
    labelEs: 'Barras',
    definition: 'Straight, Olympic, or specialty training bars.',
    positiveEvidence: ['name contains "barra" (excluding paralelas/dominadas/pull-up wording)'],
    negativeEvidence: ['pull-up/parallel bars (BODYWEIGHT_GYMNASTICS)', 'installation/service SKUs mentioning "barra"'],
    allowedEvidenceSources: ['NAME_TEXT'],
    confidencePolicy: {
      allowedConfidenceLevels: ['EXPLICIT'],
      notes: 'EXPLICIT when name matches; no category fallback needed given high name coverage.',
    },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous (e.g. "Barra OlÃ­mpica 20kg").' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'WEIGHT_PLATE',
    labelEs: 'Discos y Bumpers',
    definition: 'Iron, bumper, fractional, or Crumb Bumper plates.',
    positiveEvidence: ['name contains "disco"/"bumper"/"fraccional"', 'trusted category (Discos*, Bumper Plates)'],
    negativeEvidence: ['dumbbells, kettlebells'],
    allowedEvidenceSources: ['NAME_TEXT', 'TRUSTED_CATEGORY'],
    confidencePolicy: {
      allowedConfidenceLevels: ['EXPLICIT', 'STRONGLY_INFERRED'],
      notes: 'EXPLICIT by name; STRONGLY_INFERRED by category fallback (e.g. "Pack 100kg Eco Series").',
    },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'DUMBBELL',
    labelEs: 'Mancuernas',
    definition: 'Fixed, hex, adjustable dumbbells and dumbbell sets.',
    positiveEvidence: ['name/category contains "mancuerna"'],
    negativeEvidence: ['kettlebells'],
    allowedEvidenceSources: ['NAME_TEXT', 'TRUSTED_CATEGORY'],
    confidencePolicy: {
      allowedConfidenceLevels: ['EXPLICIT', 'STRONGLY_INFERRED'],
      notes: 'EXPLICIT by name; STRONGLY_INFERRED by category (e.g. cast-iron case sets with no "mancuerna" in the name).',
    },
    historicalPolicy: {
      classifiableFromNameOnly: true,
      notes: 'Classify from name only when unambiguous; a bare "MaletÃ­n Cast Iron" name without "mancuerna" or catalog metadata stays unclassified.',
    },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'KETTLEBELL',
    labelEs: 'Kettlebells',
    definition: 'Kettlebells and clubbells.',
    positiveEvidence: ['name contains "kettlebell"/"pesa rusa"/"clubbell"'],
    negativeEvidence: ['dumbbells'],
    allowedEvidenceSources: ['NAME_TEXT'],
    confidencePolicy: { allowedConfidenceLevels: ['EXPLICIT'], notes: 'EXPLICIT.' },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'BENCH',
    labelEs: 'Bancos',
    definition: 'Flat, adjustable, and specialty benches (GHD, hip-thrust box).',
    positiveEvidence: ['name contains "banco", "GHD", "hip thrust"'],
    negativeEvidence: ['machine seats that are not standalone products'],
    allowedEvidenceSources: ['NAME_TEXT'],
    confidencePolicy: { allowedConfidenceLevels: ['EXPLICIT'], notes: 'EXPLICIT.' },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'RACK_CAGE',
    labelEs: 'Racks y Jaulas',
    definition: 'Power/squat racks, cages, stands.',
    positiveEvidence: ['name contains "power rack"/"squat rack"/"jaula"/"rack"'],
    negativeEvidence: [
      'storage racks (STORAGE)',
      'Smith machines (PLATE_LOADED_MACHINE â€” Smith-machine wording overrides RACK_CAGE even when the name says "Jaula")',
      'installation-service SKUs mentioning "jaula"',
    ],
    allowedEvidenceSources: ['NAME_TEXT'],
    confidencePolicy: { allowedConfidenceLevels: ['EXPLICIT'], notes: 'EXPLICIT.' },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'CABLE_MACHINE',
    labelEs: 'MÃ¡quinas de Poleas',
    definition: 'Cable/pulley stations.',
    positiveEvidence: ['name contains "polea"/"crossover"/"lat pulldown"/"cable"'],
    negativeEvidence: [
      'Smith-machine hybrids sold under "Smith" naming (primary family PLATE_LOADED_MACHINE; may carry CABLE_MACHINE as secondary only when the product description confirms a genuine integrated pulley system)',
    ],
    allowedEvidenceSources: ['NAME_TEXT'],
    confidencePolicy: { allowedConfidenceLevels: ['EXPLICIT'], notes: 'EXPLICIT.' },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'PLATE_LOADED_MACHINE',
    labelEs: 'MÃ¡quinas con Carga de Discos',
    definition: 'Plate-loaded machines, including all Smith-machine variants regardless of "Jaula"/"Multifuncional" naming.',
    positiveEvidence: ['name contains "prensa"/"carga de discos"/"smith"', 'trusted category "MÃ¡quinas con Carga de Discos"'],
    negativeEvidence: ['selectorized (pin-stack) machines'],
    allowedEvidenceSources: ['NAME_TEXT', 'TRUSTED_CATEGORY'],
    confidencePolicy: {
      allowedConfidenceLevels: ['EXPLICIT', 'STRONGLY_INFERRED'],
      notes: 'EXPLICIT by name (including all "Smith" naming variants); STRONGLY_INFERRED by category fallback.',
    },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'SELECTORIZED_MACHINE',
    labelEs: 'MÃ¡quinas Selectorizadas',
    definition: 'Pin-stack guided machines.',
    positiveEvidence: [
      'name contains "selectorizad"/"pila de stack"/"dual cuÃ¡driceps/femoral/abductor/aductor"',
      'trusted category "MÃ¡quinas Selectorizadas"',
    ],
    negativeEvidence: ['plate-loaded machines'],
    allowedEvidenceSources: ['NAME_TEXT', 'TRUSTED_CATEGORY'],
    confidencePolicy: {
      allowedConfidenceLevels: ['EXPLICIT', 'STRONGLY_INFERRED'],
      notes:
        "EXPLICIT by name; STRONGLY_INFERRED by category (majority of this family's population â€” verified as sound, not a false-positive pattern, in the A00.1C closure pass).",
    },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'CARDIO_MACHINE',
    labelEs: 'MÃ¡quinas de Cardio',
    definition: 'Treadmills, bikes, rowers, airbikes, ski ergs.',
    positiveEvidence: ['name contains "trotadora"/"bicicleta"/"spinning"/"airbike"/"air ski"/"eliptica"/"escaladora"'],
    negativeEvidence: [],
    allowedEvidenceSources: ['NAME_TEXT'],
    confidencePolicy: { allowedConfidenceLevels: ['EXPLICIT'], notes: 'EXPLICIT.' },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'FLOORING',
    labelEs: 'Piso y Plataformas',
    definition: 'Rubber tiles, interlock floors, platforms, impact mats, tatami.',
    positiveEvidence: ['name contains "palmeta"/"piso"/"tatami"/"colchoneta" (no yoga/pilates wording)'],
    negativeEvidence: ['yoga/pilates mats (YOGA_PILATES)'],
    allowedEvidenceSources: ['NAME_TEXT'],
    confidencePolicy: { allowedConfidenceLevels: ['EXPLICIT'], notes: 'EXPLICIT.' },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'STORAGE',
    labelEs: 'Almacenamiento',
    definition: 'Storage racks/organizers for equipment.',
    positiveEvidence: ['name/category contains "almacenamiento"/"rack vertical"/"rack para X"'],
    negativeEvidence: ['training racks (power/squat â€” RACK_CAGE)'],
    allowedEvidenceSources: ['NAME_TEXT', 'TRUSTED_CATEGORY'],
    confidencePolicy: {
      allowedConfidenceLevels: ['EXPLICIT'],
      notes:
        "EXPLICIT by name, checked before any product-type-noun family rule so a storage rack for barbells/dumbbells/plates is never misfiled as that product's own family.",
    },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'BALL_BAG',
    labelEs: 'Balones y Sacos',
    definition: 'Medicine balls, slam balls, sand bags, bosu.',
    positiveEvidence: ['name contains "balÃ³n medicinal"/"slam ball"/"sand bag"/"bosu" (no "pilates")'],
    negativeEvidence: ['pilates balls (YOGA_PILATES)'],
    allowedEvidenceSources: ['NAME_TEXT'],
    confidencePolicy: { allowedConfidenceLevels: ['EXPLICIT'], notes: 'EXPLICIT.' },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'ROPE_SLED',
    labelEs: 'Cuerdas y Trineos',
    definition: 'Climbing/battle ropes, sleds.',
    positiveEvidence: ['name contains "soga"/"cuerda"/"trineo"/"sled"'],
    negativeEvidence: ['cable-machine rope attachments sold as machine accessories'],
    allowedEvidenceSources: ['NAME_TEXT'],
    confidencePolicy: { allowedConfidenceLevels: ['EXPLICIT'], notes: 'EXPLICIT.' },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'BAND_SUSPENSION',
    labelEs: 'Bandas y SuspensiÃ³n',
    definition: 'Resistance bands, tubes, suspension anchors.',
    positiveEvidence: ['name contains "banda"/"suspension"/"tubo elÃ¡stico"/"x-mount"'],
    negativeEvidence: ['lifting straps (PROTECTIVE_GEAR)'],
    allowedEvidenceSources: ['NAME_TEXT'],
    confidencePolicy: { allowedConfidenceLevels: ['EXPLICIT'], notes: 'EXPLICIT.' },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'BODYWEIGHT_GYMNASTICS',
    labelEs: 'Calistenia y Gimnasia',
    definition: 'Pull-up/dip bars, parallettes, rings, handstand-walk ramps.',
    positiveEvidence: ['name contains "paralelas"/"dominadas"/"pull up"/"anillas"/"rampa caminata de manos"'],
    negativeEvidence: ['barbell bars'],
    allowedEvidenceSources: ['NAME_TEXT'],
    confidencePolicy: { allowedConfidenceLevels: ['EXPLICIT'], notes: 'EXPLICIT, checked before the generic BARBELL rule.' },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'PROTECTIVE_GEAR',
    labelEs: 'ProtecciÃ³n de Levantamiento',
    definition: 'Belts, sleeves, wraps, grips, gloves, boxing wraps/gloves.',
    positiveEvidence: [
      'name contains "cinturÃ³n"/"rodillera"/"muÃ±equera"/"callera"/"guante"/"vendaje"',
      'trusted category (Accesorios de ProtecciÃ³n, Boxeo & MMA gear)',
    ],
    negativeEvidence: ['apparel with no protective function'],
    allowedEvidenceSources: ['NAME_TEXT', 'TRUSTED_CATEGORY'],
    confidencePolicy: {
      allowedConfidenceLevels: ['EXPLICIT', 'STRONGLY_INFERRED'],
      notes: 'EXPLICIT by name; STRONGLY_INFERRED by category (e.g. "Vendas de Boxeo" â€” verified correct in the A00.1C closure pass).',
    },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'MACHINE_ATTACHMENT',
    labelEs: 'Accesorios de MÃ¡quina',
    definition: 'Cable/rack/bench add-ons (collars, J-cups, spotter arms, ankle straps, mount hardware).',
    positiveEvidence: ['name/category signals an add-on tied to a machine/rack/bench system'],
    negativeEvidence: [
      'standalone machines',
      '"Accesorios de Weightlifting" category (excluded â€” too broad, wrongly voted this family for chalk in an earlier draft)',
    ],
    allowedEvidenceSources: ['NAME_TEXT', 'TRUSTED_CATEGORY'],
    confidencePolicy: {
      allowedConfidenceLevels: ['EXPLICIT', 'STRONGLY_INFERRED'],
      notes: 'EXPLICIT by name; STRONGLY_INFERRED by category â€” verified as a sound, false-positive-free evidence path in the A00.1C closure pass.',
    },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'RECOVERY_TOOL',
    labelEs: 'RecuperaciÃ³n',
    definition: 'Foam rollers, massage tools, hyperbaric chambers, compression boots.',
    positiveEvidence: ['name contains "foam roller"/"masajeador"/"cÃ¡mara hiperbÃ¡rica"/"botas de compresiÃ³n"/"presoterapia"'],
    negativeEvidence: ['generic mobility tools with no recovery-device identity'],
    allowedEvidenceSources: ['NAME_TEXT'],
    confidencePolicy: { allowedConfidenceLevels: ['EXPLICIT'], notes: 'EXPLICIT.' },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'YOGA_PILATES',
    labelEs: 'Yoga y Pilates',
    definition: 'Yoga mats, pilates balls/tools.',
    positiveEvidence: ['name/category contains "yoga"/"pilates"'],
    negativeEvidence: ['generic impact/landing mats, generic flooring'],
    allowedEvidenceSources: ['NAME_TEXT', 'TRUSTED_CATEGORY'],
    confidencePolicy: { allowedConfidenceLevels: ['EXPLICIT'], notes: 'EXPLICIT.' },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'APPAREL',
    labelEs: 'Indumentaria',
    definition: 'Clothing/merch.',
    positiveEvidence: ['name contains "polera"/"crop top"/"buzo"/"polerÃ³n"/"gorra"'],
    negativeEvidence: ['protective gear'],
    allowedEvidenceSources: ['NAME_TEXT'],
    confidencePolicy: { allowedConfidenceLevels: ['EXPLICIT'], notes: 'EXPLICIT.' },
    historicalPolicy: { classifiableFromNameOnly: true, notes: 'Classify from name only when unambiguous.' },
    status: 'ACTIVE',
    residual: false,
  },
  {
    axis: 'PRODUCT_FAMILY',
    code: 'OTHER',
    labelEs: 'Otro / Sin Clasificar',
    definition: 'Residual bucket â€” no reliable evidence matched any tag above. Not a real ontology tag.',
    positiveEvidence: [],
    negativeEvidence: [],
    allowedEvidenceSources: [],
    confidencePolicy: { allowedConfidenceLevels: [], notes: 'INSUFFICIENT_EVIDENCE by construction; no confidence level applies.' },
    historicalPolicy: {
      classifiableFromNameOnly: false,
      notes: 'Ambiguous historical names (e.g. "Pack Grip 105kg", "MÃ¡quina Home Gym ULTRA FZ410") stay OTHER rather than guessed.',
    },
    status: 'RESIDUAL',
    residual: true,
  },
];
