import {readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {parseCsvRecords} from '../../product-semantic-classification/lib/csv.ts';
const out='artifacts/catalog-v2/qa1/run-20261008-bddf7f';
const csv=async f=>parseCsvRecords((await readFile(`${out}/${f}`,'utf8')).replace(/^\ufeff/u,''));
const matrix=await csv('product_semantic_matrix.csv');
const j=async f=>JSON.parse(await readFile(`${out}/${f}`,'utf8'));
const inventory=await j('ontology_inventory.json'),summary=await j('audit_summary.json');
const conflicts=await csv('cross_dimension_conflicts.csv');
const concepts=[
  ['AGILITY_PLYOMETRIC_ROLE',/\b(escalera de agilidad|valla|vallas|cono|conos|step|caj[oó]n|plyo|plataforma de salto)\b/iu,'Agility markers / hurdles / plyometric platform roles; check BODYWEIGHT_GYMNASTICS definition before proposing a family.','P2'],
  ['TIMING_MEASUREMENT_ROLE',/\b(timer|cron[oó]metro|contador|medidor)\b/iu,'Timing / measurement product role absent from current family definitions.','P2'],
  ['WEARABLE_LOAD_ROLE',/\b(lastre|peso[s]? de tobillo|peso[s]? de mu[nñ]eca|chaleco.*peso)\b/iu,'Wearable training load role; distinguish from APPAREL and WEIGHT_PLATE.','P2'],
  ['BUNDLE_COMPONENT_RELATION',/\b(pack|set)\b/iu,'Bundle-to-component relation and component quantity; a dominant family cannot state complete bundle contents.','P1'],
  ['EXISTING_FAMILY_RULE_CANDIDATE',/\b(safety squat bar|push ups|glute bands|bosu|mini tabla de escalada)\b/iu,'Existing family may suffice; lexical/evidence rules need independent review before claiming an ontology gap.','P2']
];
const rows=concepts.flatMap(([conceptId,re,description,priority])=>matrix.filter(r=>r.catalogPresence==='current_catalog'&&re.test(r.productName)&&(conceptId==='BUNDLE_COMPONENT_RELATION'||r.classificationStatus==='OTHER')).map(r=>({conceptId,productId:Number(r.productId),name:r.productName,family:r.productFamily,active:r.activeStatus==='ACTIVE',priority,description,sourceCategories:JSON.parse(r.sourceCategories),sourceFeatures:JSON.parse(r.sourceFeatures),reference:JSON.parse(r.snapshotReferences),certainty:'HYPOTHESIS',ontologyDefectProven:false,requiredAdjudication:'Independent Product Truth and registry-definition comparison; name hit is a candidate only.'})));
const fields=Object.keys(rows[0]),cell=x=>'"'+String(typeof x==='object'?JSON.stringify(x):x).replaceAll('"','""')+'"';
await writeFile(`${out}/candidate_missing_concepts.csv`,'\ufeff'+[fields.map(cell).join(','),...rows.map(r=>fields.map(k=>cell(r[k])).join(','))].join('\r\n')+'\r\n');
const conceptsSummary=concepts.map(([conceptId,,description,priority])=>({conceptId,description,priority,productIds:rows.filter(r=>r.conceptId===conceptId).map(r=>r.productId),activeProductIds:rows.filter(r=>r.conceptId===conceptId&&r.active).map(r=>r.productId),certainty:'HYPOTHESIS',ontologyDefectProven:false}));
await writeFile(`${out}/qualitative_findings.json`,JSON.stringify({concepts:conceptsSummary,structure:{familyHierarchy:'No parent-child contract; 21 recognized flat families plus residual state. Cannot infer equipment subtypes or bundle composition.',granularity:'BALL_BAG, ROPE_SLED, BAND_SUSPENSION merge roles; MACHINE_ATTACHMENT merges grips/collars/modules. Examples prove different source roles, not a required new family.',relationBoundaries:'Family is a taxonomic assignment; Training Function is instrumental; neither certifies product-to-product compatibility, dependencies or substitution.',extensibility:'Registries, rules and hashes permit extension; admission requires a complete row for every recognized family. Explicit productId exclusions and previous-policy adjudications remain non-generic dependencies.',orphanOther:'OTHER has zero tag assignments by design; 321 OTHER states retain null primary family. Do not treat residual code as a defect.'},reviewLimit:'All 280 dossiers are ready for human review. This pass formulates source-grounded hypotheses, not independent correctness labels.'},null,2)+'\n');
const writeCsv=async (f,data,fields=Object.keys(data[0]))=>writeFile(`${out}/${f}`,'\ufeff'+[fields.map(cell).join(','),...data.map(r=>fields.map(k=>cell(r[k])).join(','))].join('\r\n')+'\r\n');
const cable=matrix.filter(r=>r.productFamily==='CABLE_MACHINE'&&r.trainingV2ResolutionState==='VERIFIED_NO_APPLICABLE_CAPABILITY');
const historicalConflict=conflicts.filter(c=>c.dimensions==='PRODUCT_SEMANTICS');
const newIssues=[{issueId:'CABLE_FAMILY_FUNCTION_BOUNDARY',priority:'P1',severity:'HIGH',productCount:cable.length,currentCount:cable.filter(r=>r.catalogPresence==='current_catalog').length,activeExposure:cable.filter(r=>r.activeStatus==='ACTIVE').length,productIds:cable.map(r=>Number(r.productId)),activeProductIds:cable.filter(r=>r.activeStatus==='ACTIVE').map(r=>Number(r.productId)),concept:'Separate cable station, cable-resistance module and passive cable accessory roles',rootCause:'ONTOLOGY_GRANULARITY_AND_RULE_PRECEDENCE',retrievalImpact:'PF_CABLE_MACHINE_NAME_V1 explicitly includes pulley accessories, but family obligation requires CABLE_RESISTANCE; passive grips/ropes fail the function obligation.',recommendationRisk:'Family-only type search can imply a machine; Function Admission blocks the unsupported function. No published false technical statement proven.',evidence:cable.map(r=>({productId:Number(r.productId),product:JSON.parse(r.productEvidence),obligations:JSON.parse(r.applicableSemanticObligations),training:JSON.parse(r.trainingEvidenceStatus),reference:JSON.parse(r.snapshotReferences)})),evidenceAvailable:'MEASURED contract/rule tension; passive role adjudication INFERRED',dependencies:'Review CABLE_MACHINE/MACHINE_ATTACHMENT role boundary and family obligation in a separate approved change',nextAction:'Adjudicate exact passive-accessory IDs against cable station versus module definitions; do not delete valid integrated CABLE_RESISTANCE such as P1124',certainty:'MEASURED structural tension; independent correctness not adjudicated',implemented:false},
{issueId:'HISTORICAL_DISCIPLINE_INFERENCE',priority:'P2',severity:'MEDIUM',productCount:historicalConflict.length,currentCount:0,activeExposure:0,productIds:historicalConflict.map(c=>Number(c.productId)),activeProductIds:[],concept:'Historical explicit-name discipline policy versus FAMILY_INFERENCE',rootCause:'RULE_POLICY_PROVENANCE',retrievalImpact:'Historical snapshots can infer CALISTHENICS/CARDIO_ENDURANCE from family, while Admission maps this as SOURCE_CONFLICT.',recommendationRisk:'No active exposure; do not merge historical and current evidence claims',evidence:historicalConflict,evidenceAvailable:'MEASURED; code paths documented',dependencies:'Resolve explicit historical policy versus permitted family inference in a separate review',nextAction:'Inspect exact conflicting historical IDs; align intended policy after independent adjudication',certainty:'MEASURED',implemented:false}];
for(const c of conceptsSummary)newIssues.push({issueId:c.conceptId,priority:c.priority,severity:c.priority==='P1'?'HIGH':'MEDIUM',productCount:c.productIds.length,currentCount:c.productIds.length,activeExposure:c.activeProductIds.length,productIds:c.productIds,activeProductIds:c.activeProductIds,concept:c.description,rootCause:c.conceptId==='EXISTING_FAMILY_RULE_CANDIDATE'?'CLASSIFICATION_RULE_HYPOTHESIS':'ONTOLOGY_CANDIDATE',retrievalImpact:c.description,recommendationRisk:'Potential incomplete type retrieval; bundle composition requires component evidence',evidence:rows.filter(r=>r.conceptId===c.conceptId),evidenceAvailable:c.certainty,dependencies:'Independent source adjudication and vocabulary-definition review',nextAction:'Review listed IDs and feature/category provenance; establish whether an existing concept is adequate before proposing a registry extension',certainty:c.certainty,implemented:false});
const original=await csv('prioritized_remediation_backlog.csv');
const additions=new Map(newIssues.map(b=>[b.issueId,b]));
const combined=[...original.filter(b=>!additions.has(b.issueId)),...newIssues].toSorted((a,b)=>a.priority.localeCompare(b.priority)||Number(b.activeExposure)-Number(a.activeExposure)||a.issueId.localeCompare(b.issueId));
await writeCsv('prioritized_remediation_backlog.csv',combined,Object.keys(original[0]));
summary.backlog=combined.map(b=>Object.fromEntries(Object.entries(b).filter(([k])=>k!=='evidence').map(([k,v])=>[k,typeof v==='string'&&['productIds','activeProductIds'].includes(k)?JSON.parse(v):v])));
summary.qualitativeConcepts=conceptsSummary;summary.cableBoundary={products:cable.length,current:cable.filter(r=>r.catalogPresence==='current_catalog').length,active:cable.filter(r=>r.activeStatus==='ACTIVE').length,productIds:cable.map(r=>Number(r.productId))};summary.historicalInferenceConflict={products:historicalConflict.length,productIds:historicalConflict.map(r=>Number(r.productId))};
await writeFile(`${out}/audit_summary.json`,JSON.stringify(summary,null,2)+'\n');
// Distinguish a definition/rule tension from a confirmed product-label error.
const structural=matrix.filter(r=>cable.some(c=>c.productId===r.productId)).map(r=>({productId:r.productId,family:r.productFamily,active:r.activeStatus==='ACTIVE',dimensions:'PRODUCT_FAMILY/TRAINING_FUNCTION',kind:'CABLE_ROLE_OBLIGATION_TENSION',cause:'ONTOLOGY_GRANULARITY_AND_RULE_PRECEDENCE',evidence:{familyRule:JSON.parse(r.productEvidence),functionObligation:JSON.parse(r.applicableSemanticObligations).find(d=>d.dimension==='TRAINING_FUNCTION'),trainingState:r.trainingV2ResolutionState},certainty:'MEASURED structural tension; semantic label correctness INFERRED',requiresHumanAdjudication:true,sourceReference:JSON.parse(r.snapshotReferences)}));
const existing=conflicts.filter(c=>c.kind!=='CABLE_ROLE_OBLIGATION_TENSION');await writeCsv('cross_dimension_conflicts.csv',[...existing,...structural],Object.keys(conflicts[0]));
const sampleCases=await j('qa2_sample_cases.json');
for(const r of sampleCases) {r.possiblyAbsentConcepts.push(...rows.filter(c=>c.productId===r.productId).map(c=>({issueId:c.conceptId,concept:c.description,certainty:c.certainty})));r.detectedContradictions.push(...structural.filter(c=>Number(c.productId)===r.productId));}
await writeFile(`${out}/qa2_sample_cases.json`,JSON.stringify(sampleCases,null,2)+'\n');await writeCsv('qa2_review_sample.csv',sampleCases);
await writeFile(`${out}/structural_consistency_checks.json`,JSON.stringify({cableBoundary:summary.cableBoundary,historicalInference:summary.historicalInferenceConflict,exerciseSpecConsistency:{status:'UNKNOWN',reason:'No registry encodes necessary physical spec minima for every exercise; absence of Specs cannot prove capability incompatibility.'},sourceFamilyConsistency:{status:'PARTIAL',reason:'Taxonomic categories may be weak/campaign/overlapping; no universal category-to-family truth relation. All source/evidence retained.'},disciplineContextConsistency:{status:'UNKNOWN',reason:'No disjointness/exclusivity contract; home and commercial tags may coexist legitimately.'},granularity:{examples:rows.filter(r=>['AGILITY_PLYOMETRIC_ROLE','WEARABLE_LOAD_ROLE','BUNDLE_COMPONENT_RELATION'].includes(r.conceptId)).map(({sourceFeatures,...r})=>r)},extensibility:{ontologyProductIdExceptions:inventory.ontology.globalRules.nonProductExclusionPolicy??inventory.ontology.globalRules.nonProductExclusion,trainingPolicyInputs:'C.inputs.resolutionPolicy.previousPolicy binds historical product-level adjudications; not all generalization is registry driven.',status:'PARTIAL'},basis:'MEASURED structural checks; product truth correctness NOT_MEASURABLE'},null,2)+'\n');
console.log(JSON.stringify({concepts:conceptsSummary.map(c=>({id:c.conceptId,n:c.productIds.length,active:c.activeProductIds.length})),cable:summary.cableBoundary,historicalConflict:summary.historicalInferenceConflict}));
// A CSV round-trip validates the matrix population and the dossier identifiers.
assert.equal(matrix.length,2048);assert.equal(new Set(matrix.map(r=>r.productId)).size,2048);
const sample=await csv('qa2_review_sample.csv');assert.equal(sample.length,280);assert.equal(new Set(sample.map(r=>r.productId)).size,280);
assert(sample.every(r=>matrix.some(m=>m.productId===r.productId)));assert.equal(sample.filter(r=>r.subset==='STRATIFIED_RANDOM').length,160);
const fixed=[1020,1856,247,897,1624,1124,1812,1999,2008,1543,435,930,1354,899,1365];assert(fixed.every(id=>sample.some(r=>Number(r.productId)===id)));
console.log('CSV/DOSSIER_SELF_CHECK=PASS');
