// GENERATED by scripts/catalog-v2/generate-category-trust-map.mjs — do not edit by hand.
// Source: docs/audits/product-intelligence-exploration/inputs/category_trust_map(1).csv (sha256 200ad175676d52e65fa925086cf07e092713b0086ac8db7ef5cd6301747e1664).
// Keys are PRODUCTION PrestaShop category ids from the category trust audit.

export const CATEGORY_TRUST_MAP_VERSION = 'category-trust-v1+200ad175676d';

export type MeaningfulCategoryTrust = 'SEMANTIC_STRONG' | 'SEMANTIC_WEAK';

export const CATEGORY_TRUST_BY_ID: ReadonlyMap<number, MeaningfulCategoryTrust> = new Map<number, MeaningfulCategoryTrust>([
  [64, 'SEMANTIC_STRONG'], // Mancuernas Hexagonales
  [65, 'SEMANTIC_STRONG'], // Kettlebells
  [66, 'SEMANTIC_STRONG'], // Bumper Plates
  [67, 'SEMANTIC_STRONG'], // Barras Olímpicas
  [68, 'SEMANTIC_STRONG'], // Power Racks y Bancos
  [69, 'SEMANTIC_STRONG'], // Gimnasia y Acondicionamiento
  [143, 'SEMANTIC_STRONG'], // Accesorios y Complementos
  [248, 'SEMANTIC_WEAK'], // FUERZA
  [249, 'SEMANTIC_STRONG'], // Barras Hombre 20 kg
  [250, 'SEMANTIC_STRONG'], // Barras Mujer 15 kg
  [251, 'SEMANTIC_STRONG'], // Barras Técnicas
  [252, 'SEMANTIC_STRONG'], // Barras Junior
  [253, 'SEMANTIC_STRONG'], // Barras Especiales
  [254, 'SEMANTIC_STRONG'], // Barras Powerlifting
  [255, 'SEMANTIC_STRONG'], // Barras Preolímpicas
  [256, 'SEMANTIC_STRONG'], // Barras de Peso Fijo
  [258, 'SEMANTIC_STRONG'], // Barras
  [259, 'SEMANTIC_STRONG'], // Discos
  [260, 'SEMANTIC_STRONG'], // Discos Bumper
  [261, 'SEMANTIC_STRONG'], // Discos de Competición
  [262, 'SEMANTIC_STRONG'], // Discos Fraccionados
  [263, 'SEMANTIC_STRONG'], // Discos Con Agarre
  [264, 'SEMANTIC_STRONG'], // Discos de Acero
  [265, 'SEMANTIC_STRONG'], // Discos de Powerlifting
  [266, 'SEMANTIC_STRONG'], // Discos Preolímpicos
  [267, 'SEMANTIC_STRONG'], // Mancuernas
  [268, 'SEMANTIC_STRONG'], // Mancuernas Hexagonales
  [269, 'SEMANTIC_STRONG'], // Mancuernas Pu
  [270, 'SEMANTIC_STRONG'], // Mancuernas de Acero
  [271, 'SEMANTIC_STRONG'], // Mancuernas de Neopreno
  [272, 'SEMANTIC_STRONG'], // Mancuernas Ajustables
  [273, 'SEMANTIC_STRONG'], // Set de Mancuernas
  [274, 'SEMANTIC_STRONG'], // Set de Barras
  [275, 'SEMANTIC_STRONG'], // Accesorios para Barras
  [276, 'SEMANTIC_STRONG'], // Kettlebells
  [277, 'SEMANTIC_STRONG'], // Kettlebells de Acero
  [278, 'SEMANTIC_STRONG'], // Kettlebells de Vinilo
  [279, 'SEMANTIC_STRONG'], // Clubells
  [280, 'SEMANTIC_WEAK'], // EQUIPAMIENTO
  [281, 'SEMANTIC_STRONG'], // Máquinas Selectorizadas
  [285, 'SEMANTIC_STRONG'], // Máquinas con Carga de Discos
  [290, 'SEMANTIC_STRONG'], // Máquinas con Poleas
  [291, 'SEMANTIC_WEAK'], // Máquinas Multifuncionales
  [292, 'SEMANTIC_WEAK'], // Accesorios para Máquinas
  [293, 'SEMANTIC_STRONG'], // Racks
  [294, 'SEMANTIC_STRONG'], // Power Racks
  [295, 'SEMANTIC_STRONG'], // Half Racks
  [296, 'SEMANTIC_STRONG'], // Squat Racks
  [297, 'SEMANTIC_STRONG'], // Atriles
  [298, 'SEMANTIC_STRONG'], // Powerlifting Racks
  [299, 'SEMANTIC_STRONG'], // Wall Racks
  [300, 'SEMANTIC_STRONG'], // Accesorios para Racks
  [301, 'SEMANTIC_STRONG'], // Bancos
  [302, 'SEMANTIC_STRONG'], // Bancos Olímpicos
  [303, 'SEMANTIC_STRONG'], // Bancos Planos
  [304, 'SEMANTIC_STRONG'], // Bancos Ajustables
  [305, 'SEMANTIC_STRONG'], // Bancos Ergo
  [306, 'SEMANTIC_STRONG'], // Bancos Abdominales
  [307, 'SEMANTIC_STRONG'], // Bancos Especiales
  [308, 'SEMANTIC_STRONG'], // Cardio
  [309, 'SEMANTIC_STRONG'], // Trotadoras
  [310, 'SEMANTIC_STRONG'], // Elípticas
  [311, 'SEMANTIC_STRONG'], // Escaladoras
  [312, 'SEMANTIC_STRONG'], // Bicicletas
  [313, 'SEMANTIC_STRONG'], // Remos & Ski
  [314, 'SEMANTIC_STRONG'], // Máquinas Home Gym
  [315, 'SEMANTIC_STRONG'], // Accesorios para Bancos
  [317, 'SEMANTIC_WEAK'], // ACONDICIONAMIENTO
  [318, 'SEMANTIC_STRONG'], // Balones & Sacos
  [319, 'SEMANTIC_STRONG'], // Barras Pull Up & Push Up
  [320, 'SEMANTIC_STRONG'], // Bandas
  [321, 'SEMANTIC_STRONG'], // Cuerdas
  [322, 'SEMANTIC_STRONG'], // Lastre
  [323, 'SEMANTIC_WEAK'], // Gimnasia & Funcional
  [341, 'SEMANTIC_STRONG'], // PISO
  [342, 'SEMANTIC_STRONG'], // Palmetas de Caucho
  [343, 'SEMANTIC_STRONG'], // Pisos Interlock
  [344, 'SEMANTIC_STRONG'], // Rollos de Caucho
  [345, 'SEMANTIC_STRONG'], // Pasto Sintético
  [346, 'SEMANTIC_STRONG'], // Crash Pads
  [347, 'SEMANTIC_STRONG'], // Plataformas de Levantamiento
  [348, 'SEMANTIC_WEAK'], // ACCESORIOS
  [349, 'SEMANTIC_WEAK'], // Accesorios de Protección
  [350, 'SEMANTIC_STRONG'], // Calleras
  [351, 'SEMANTIC_STRONG'], // Cinturones de Levantamiento
  [352, 'SEMANTIC_STRONG'], // Muñequeras
  [353, 'SEMANTIC_STRONG'], // Rodilleras
  [354, 'SEMANTIC_STRONG'], // Correas de Levantamiento
  [355, 'SEMANTIC_STRONG'], // Abdominales
  [356, 'SEMANTIC_STRONG'], // Agarres OCR
  [359, 'SEMANTIC_STRONG'], // Botellas & Shakers
  [362, 'SEMANTIC_STRONG'], // Elevadores de Talones
  [363, 'SEMANTIC_STRONG'], // Magnesio
  [364, 'SEMANTIC_STRONG'], // Timers
  [365, 'SEMANTIC_STRONG'], // Ventiladores
  [366, 'SEMANTIC_STRONG'], // RECOVERY
  [367, 'SEMANTIC_STRONG'], // Cámaras Hiperbáricas
  [368, 'SEMANTIC_STRONG'], // Foam Rollers
  [369, 'SEMANTIC_STRONG'], // Masajeadores
  [370, 'SEMANTIC_STRONG'], // Pistolas de Masaje
  [371, 'SEMANTIC_STRONG'], // Presoterapia
  [372, 'SEMANTIC_STRONG'], // Vendaje K-Tape
  [373, 'SEMANTIC_STRONG'], // ALMACENAMIENTO
  [374, 'SEMANTIC_STRONG'], // Racks para Balones
  [375, 'SEMANTIC_STRONG'], // Racks para Barras
  [376, 'SEMANTIC_STRONG'], // Racks para Discos
  [377, 'SEMANTIC_STRONG'], // Racks para Kettlebells
  [378, 'SEMANTIC_STRONG'], // Racks para Mancuernas
  [379, 'SEMANTIC_WEAK'], // APPAREL
  [380, 'SEMANTIC_STRONG'], // Poleras
  [381, 'SEMANTIC_STRONG'], // Polerones
  [382, 'SEMANTIC_STRONG'], // Gorras
  [383, 'SEMANTIC_STRONG'], // Mochilas & Bolsos
  [384, 'SEMANTIC_STRONG'], // Llaveros
  [385, 'SEMANTIC_STRONG'], // Pulseras
  [386, 'SEMANTIC_WEAK'], // PACKS
  [387, 'SEMANTIC_WEAK'], // Packs de Discos, Barras & Mancuernas
  [389, 'SEMANTIC_WEAK'], // Packs Garage Gym
  [390, 'SEMANTIC_WEAK'], // Packs Gimnasio
  [391, 'SEMANTIC_WEAK'], // Otros Packs
  [411, 'SEMANTIC_STRONG'], // Powerlifting
  [412, 'SEMANTIC_STRONG'], // Calistenia
  [414, 'SEMANTIC_STRONG'], // Yoga & Pilates
  [424, 'SEMANTIC_STRONG'], // Balones de Pilates
  [425, 'SEMANTIC_STRONG'], // Balones Medicinales
  [426, 'SEMANTIC_STRONG'], // Bosu
  [427, 'SEMANTIC_STRONG'], // Slam Balls
  [428, 'SEMANTIC_STRONG'], // Sand Bags
  [429, 'SEMANTIC_STRONG'], // Barras de Dominadas
  [430, 'SEMANTIC_STRONG'], // Barras Paralelas
  [431, 'SEMANTIC_STRONG'], // Bandas de Resistencia
  [432, 'SEMANTIC_STRONG'], // Glute Bands
  [433, 'SEMANTIC_STRONG'], // Tubos Elásticos
  [434, 'SEMANTIC_STRONG'], // Cuerdas de Salto
  [435, 'SEMANTIC_STRONG'], // Battle Ropes
  [436, 'SEMANTIC_STRONG'], // Sogas de Trepa
  [437, 'SEMANTIC_STRONG'], // Chalecos de Lastre
  [438, 'SEMANTIC_STRONG'], // Cinturones de Lastre
  [439, 'SEMANTIC_STRONG'], // Cinturones para Hip Thrust
  [440, 'SEMANTIC_STRONG'], // Pesos de Tobillo & Muñeca
  [441, 'SEMANTIC_STRONG'], // Body Pump
  [442, 'SEMANTIC_STRONG'], // Anillas & Bandas de Suspensión
  [443, 'SEMANTIC_STRONG'], // Colchonetas & Mats
  [444, 'SEMANTIC_STRONG'], // Cajones de Salto
  [445, 'SEMANTIC_STRONG'], // Escaleras & Conos de Agilidad
  [446, 'SEMANTIC_STRONG'], // Step Aeróbicos
  [447, 'SEMANTIC_STRONG'], // Tablas de Escalada
  [448, 'SEMANTIC_STRONG'], // Trineos de Arrastre
  [449, 'SEMANTIC_STRONG'], // Vallas de Salto
  [450, 'SEMANTIC_STRONG'], // Guantes
  [451, 'SEMANTIC_STRONG'], // Accesorios de Polea
  [465, 'SEMANTIC_STRONG'], // Pantalones
  [467, 'SEMANTIC_STRONG'], // Boxeo & MMA
  [468, 'SEMANTIC_STRONG'], // Vendaje
  [472, 'SEMANTIC_STRONG'], // Martillos
  [478, 'SEMANTIC_STRONG'], // Accesorios de Weightlifting
  [493, 'SEMANTIC_STRONG'], // HYROX
  [494, 'SEMANTIC_WEAK'], // Discos & Barras
  [495, 'SEMANTIC_WEAK'], // Funcional
  [496, 'SEMANTIC_WEAK'], // Máquinas
  [497, 'SEMANTIC_STRONG'], // Mancuernas
  [500, 'SEMANTIC_WEAK'], // Accesorios
]);
